paths:
  raw: "data/raw/heart_cleveland_upload.csv"
  clean: "data/interim/clean_data.csv"
  featured: "data/processed/featured_data.csv"
  processed: "data/processed/"
  interim: "data/interim/"

values:
  categorical:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"