data:
  x_train: data/processed/X_train.csv
  x_test: data/processed/X_test.csv
  y_train: data/processed/y_train.csv
  y_test: data/processed/y_test.csv

params:
  # model_type: LogisticRegression
  # model_type: KNeighborsClassifier
  # model_type: GaussianNB
  # model_type: DecisionTreeClassifier
  # model_type: SVC
  # model_type: RandomForestClassifier
  random_state: 3
  n_neighbors: 2

save_paths:
  models: models/
  metrics: models/metrics/