data:
  x_train: data/processed/X_train.csv
  x_test: data/processed/X_test.csv
  y_train: data/processed/y_train.csv
  y_test: data/processed/y_test.csv

params:
  model_type: KNeighborsClassifier
  random_state: 3
  n_neighbors: 2